name: release
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf
        with:
          distribution: goreleaser
          version: 2.6.1
          args: --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
